//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yokanjeo.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ImagenMuestra
    {
        public int DiapositivaId { get; set; }
        public string DiapositivaTitulo { get; set; }
        public string DiapositivaImagen { get; set; }
    }
}
