//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yokanjeo.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tbl_Propiedad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Propiedad()
        {
            this.Tbl_Venta = new HashSet<Tbl_Venta>();
        }

        [Key]
        public int PropiedadId { get; set; }
        public string PropiedadNombre { get; set; }
        public Nullable<int> Tipoid { get; set; }
        public Nullable<int> Numero_habitaciones { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<bool> Eliminar { get; set; }
        public Nullable<decimal> metro_cuadrado { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> ModificaCreacion { get; set; }
        public string Descripcion { get; set; }
        public string PropiedadImagen { get; set; }
        public Nullable<bool> Destacado { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string Comuna { get; set; }
    
        public virtual Tbl_Tipo Tbl_Tipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Venta> Tbl_Venta { get; set; }
    }
}
